import { types } from 'mobx-state-tree'

export const ArtistDesc = types.model('ArtistDesc', {
  introduction: types.array(
    types.model({
      ti: types.string,
      txt: types.string,
    }),
  ),
  briefDesc: types.string,
  count: types.number,
  topicData: types.array(
    types.model({
      topic: types.model({
        id: types.number,
        addTime: types.number,
        mainTitle: types.string,
        title: types.string,
        content: types.array(
          types.model({
            type: types.number,
            id: types.number,
            content: types.string,
          }),
        ),
        userId: types.number,
        cover: types.number,
        headPic: types.number,
        shareContent: types.string,
        wxTitle: types.string,
        showComment: types.boolean,
        status: types.number,
        seriesId: types.number,
        pubTime: types.number,
        readCount: types.number,
        tags: types.array(types.string),
        pubImmidiatly: types.boolean,
        auditor: types.string,
        auditTime: types.number,
        auditStatus: types.number,
        startText: types.string,
        delReason: types.string,
        showRelated: types.boolean,
        fromBackend: types.boolean,
        rectanglePic: types.number,
        updateTime: types.number,
        reward: types.boolean,
        summary: types.string,
        memo: types.null,
        adInfo: types.string,
        categoryId: types.number,
        hotScore: types.number,
        recomdTitle: types.string,
        recomdContent: types.string,
        number: types.number,
      }),
      creator: types.model({
        userId: types.number,
        userType: types.number,
        nickname: types.string,
        avatarImgId: types.number,
        avatarUrl: types.string,
        backgroundImgId: types.number,
        backgroundUrl: types.string,
        signature: types.string,
        createTime: types.number,
        userName: types.string,
        accountType: types.number,
        shortUserName: types.string,
        birthday: types.number,
        authority: types.number,
        gender: types.number,
        accountStatus: types.number,
        province: types.number,
        city: types.number,
        authStatus: types.number,
        description: types.null,
        detailDescription: types.null,
        defaultAvatar: types.boolean,
        expertTags: types.null,
        experts: types.null,
        djStatus: types.number,
        locationStatus: types.number,
        vipType: types.number,
        followed: types.boolean,
        mutual: types.boolean,
        authenticated: types.boolean,
        lastLoginTime: types.number,
        lastLoginIP: types.string,
        remarkName: types.null,
        viptypeVersion: types.number,
        authenticationTypes: types.number,
        avatarDetail: types.null,
        anchor: types.boolean,
      }),
      shareCount: types.number,
      commentCount: types.number,
      likedCount: types.number,
      liked: types.boolean,
      rewardCount: types.number,
      rewardMoney: types.number,
      relatedResource: types.null,
      rectanglePicUrl: types.string,
      coverUrl: types.string,
      categoryId: types.number,
      categoryName: types.string,
      commentThreadId: types.string,
      reward: types.boolean,
      mainTitle: types.string,
      memo: types.null,
      summary: types.string,
      recmdTitle: types.string,
      recmdContent: types.string,
      shareContent: types.string,
      wxTitle: types.string,
      addTime: types.number,
      seriesId: types.number,
      showComment: types.boolean,
      showRelated: types.boolean,
      tags: types.array(types.string),
      readCount: types.number,
      url: types.string,
      title: types.string,
      id: types.number,
      number: types.number,
    }),
  ),
})
