import { types } from 'mobx-state-tree'

export const Chart = types.model({
  adType: types.number,
  anonimous: types.boolean,
  artists: types.null,
  backgroundCoverId: types.number,
  backgroundCoverUrl: types.null,
  cloudTrackCount: types.number,
  commentThreadId: types.string,
  coverImgId_str: types.string,
  coverImgId: types.number,
  coverImgUrl: types.string,
  createTime: types.number,
  creator: types.null,
  description: types.string,
  englishTitle: types.null,
  highQuality: types.boolean,
  id: types.number,
  name: types.string,
  newImported: types.boolean,
  opRecommend: types.boolean,
  ordered: types.boolean,
  playCount: types.number,
  privacy: types.number,
  recommendInfo: types.null,
  specialType: types.number,
  status: types.number,
  subscribed: types.null,
  subscribedCount: types.number,
  subscribers: types.array(types.null),
  tags: types.array(types.null),
  titleImage: types.number,
  titleImageUrl: types.null,
  ToplistType: types.string,
  totalDuration: types.number,
  trackCount: types.number,
  trackNumberUpdateTime: types.number,
  tracks: types.null,
  trackUpdateTime: types.number,
  updateFrequency: types.string,
  updateTime: types.number,
  userId: types.number,
})
