export { default as Header } from './Header'
export { default as PlayPanel } from './PlayPanel'
export { default as Shortcutbar } from './Shortcutbar'
export { default as Sidebar } from './Sidebar'
export { default as Statusbar } from './Statusbar'
