import { types } from 'mobx-state-tree'

import { Creator } from './Creator'

export const Playlist = types.model({
  subscribers: types.array(types.frozen()),
  subscribed: types.boolean,
  creator: Creator,
  artists: types.null,
  tracks: types.null,
  updateFrequency: types.null,
  backgroundCoverId: types.number,
  backgroundCoverUrl: types.null,
  titleImage: types.number,
  titleImageUrl: types.null,
  englishTitle: types.null,
  opRecommend: types.boolean,
  recommendInfo: types.null,
  description: types.null,
  status: types.number,
  createTime: types.number,
  highQuality: types.boolean,
  subscribedCount: types.number,
  cloudTrackCount: types.number,
  adType: types.number,
  trackNumberUpdateTime: types.number,
  specialType: types.number,
  newImported: types.boolean,
  anonimous: types.boolean,
  userId: types.number,
  coverImgUrl: types.string,
  coverImgId: types.number,
  updateTime: types.number,
  trackCount: types.number,
  commentThreadId: types.string,
  playCount: types.number,
  trackUpdateTime: types.number,
  totalDuration: types.number,
  privacy: types.number,
  ordered: types.boolean,
  tags: types.array(types.frozen()),
  name: types.string,
  id: types.number,
  coverImgId_str: types.string,
})
