import { types } from 'mobx-state-tree'

export const Profile = types.model('Profile', {
  userId: types.number,
  userType: types.number,
  nickname: types.string,
  avatarImgId: types.number,
  avatarUrl: types.string,
  backgroundImgId: types.number,
  backgroundUrl: types.string,
  signature: types.string,
  createTime: types.number,
  userName: types.string,
  accountType: types.number,
  shortUserName: types.string,
  birthday: types.number,
  authority: types.number,
  gender: types.number,
  accountStatus: types.number,
  province: types.number,
  city: types.number,
  authStatus: types.number,
  description: types.null,
  detailDescription: types.null,
  defaultAvatar: types.boolean,
  expertTags: types.null,
  experts: types.null,
  djStatus: types.number,
  locationStatus: types.number,
  vipType: types.number,
  followed: types.boolean,
  mutual: types.boolean,
  authenticated: types.boolean,
  lastLoginTime: types.number,
  lastLoginIP: types.string,
  remarkName: types.null,
  viptypeVersion: types.number,
  authenticationTypes: types.number,
  avatarDetail: types.null,
  anchor: types.boolean,
})
